// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: annotations.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class CanvasObject_Comment;
@class CanvasObject_Stroke;
@class CanvasObject_Stroke_Pen;
@class CanvasObject_Text;
@class CanvasObject_VoiceNote;
@class Dimensions;
@class GPBTimestamp;
@class Point_Class;
@class RGBColor;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CanvasObject_CanvasType

typedef GPB_ENUM(CanvasObject_CanvasType) {
  CanvasObject_CanvasType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  CanvasObject_CanvasType_None = 0,
  CanvasObject_CanvasType_Ink = 1,
  CanvasObject_CanvasType_Comment = 2,
  CanvasObject_CanvasType_TextOnPage = 3,
  CanvasObject_CanvasType_VoiceNote = 4,
};

GPBEnumDescriptor *CanvasObject_CanvasType_EnumDescriptor(void);

BOOL CanvasObject_CanvasType_IsValidValue(int32_t value);

#pragma mark - Enum CanvasObject_Stroke_Pen_Mask

typedef GPB_ENUM(CanvasObject_Stroke_Pen_Mask) {
  CanvasObject_Stroke_Pen_Mask_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  CanvasObject_Stroke_Pen_Mask_None = 0,
  CanvasObject_Stroke_Pen_Mask_Eraser = 1,
};

GPBEnumDescriptor *CanvasObject_Stroke_Pen_Mask_EnumDescriptor(void);

BOOL CanvasObject_Stroke_Pen_Mask_IsValidValue(int32_t value);

#pragma mark - Enum CanvasObject_Text_TextAlignment

typedef GPB_ENUM(CanvasObject_Text_TextAlignment) {
  CanvasObject_Text_TextAlignment_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  CanvasObject_Text_TextAlignment_Left = 0,
  CanvasObject_Text_TextAlignment_Center = 1,
  CanvasObject_Text_TextAlignment_Right = 2,
};

GPBEnumDescriptor *CanvasObject_Text_TextAlignment_EnumDescriptor(void);

BOOL CanvasObject_Text_TextAlignment_IsValidValue(int32_t value);

#pragma mark - AnnotationsRoot

@interface AnnotationsRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Session

typedef GPB_ENUM(Session_FieldNumber) {
  Session_FieldNumber_Version = 1,
  Session_FieldNumber_ClientId = 2,
  Session_FieldNumber_CanvasObjectsArray = 3,
};

@interface Session : GPBMessage

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

// |canvasObjectsArray| contains |CanvasObject|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *canvasObjectsArray;
@property(nonatomic, readonly) NSUInteger canvasObjectsArray_Count;

@end

#pragma mark - CanvasObject

typedef GPB_ENUM(CanvasObject_FieldNumber) {
  CanvasObject_FieldNumber_Type = 1,
  CanvasObject_FieldNumber_Id_p = 2,
  CanvasObject_FieldNumber_Active = 3,
  CanvasObject_FieldNumber_Shared = 4,
  CanvasObject_FieldNumber_Page = 5,
  CanvasObject_FieldNumber_Position = 6,
  CanvasObject_FieldNumber_Layer = 7,
  CanvasObject_FieldNumber_CreatedTimeStamp = 8,
  CanvasObject_FieldNumber_UpdatedTimeStamp = 9,
  CanvasObject_FieldNumber_PublishedTimeStamp = 10,
  CanvasObject_FieldNumber_Stroke = 11,
  CanvasObject_FieldNumber_Comment = 12,
  CanvasObject_FieldNumber_TextOnPage = 13,
  CanvasObject_FieldNumber_VoiceNote = 14,
};

typedef GPB_ENUM(CanvasObject_Data_OneOfCase) {
  CanvasObject_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  CanvasObject_Data_OneOfCase_Stroke = 11,
  CanvasObject_Data_OneOfCase_Comment = 12,
  CanvasObject_Data_OneOfCase_TextOnPage = 13,
  CanvasObject_Data_OneOfCase_VoiceNote = 14,
};

@interface CanvasObject : GPBMessage

@property(nonatomic, readwrite) CanvasObject_CanvasType type;

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) BOOL active;

@property(nonatomic, readwrite) BOOL shared;

@property(nonatomic, readwrite) int32_t page;

@property(nonatomic, readwrite) BOOL hasPosition;
@property(nonatomic, readwrite, strong, null_resettable) Point_Class *position;

@property(nonatomic, readwrite) int32_t layer;

@property(nonatomic, readwrite) BOOL hasCreatedTimeStamp;
@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *createdTimeStamp;

@property(nonatomic, readwrite) BOOL hasUpdatedTimeStamp;
@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *updatedTimeStamp;

@property(nonatomic, readwrite) BOOL hasPublishedTimeStamp;
@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *publishedTimeStamp;

@property(nonatomic, readonly) CanvasObject_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) CanvasObject_Stroke *stroke;

@property(nonatomic, readwrite, strong, null_resettable) CanvasObject_Comment *comment;

@property(nonatomic, readwrite, strong, null_resettable) CanvasObject_Text *textOnPage;

@property(nonatomic, readwrite, strong, null_resettable) CanvasObject_VoiceNote *voiceNote;

@end

int32_t CanvasObject_Type_RawValue(CanvasObject *message);
void SetCanvasObject_Type_RawValue(CanvasObject *message, int32_t value);

void CanvasObject_ClearDataOneOfCase(CanvasObject *message);

#pragma mark - CanvasObject_Stroke

typedef GPB_ENUM(CanvasObject_Stroke_FieldNumber) {
  CanvasObject_Stroke_FieldNumber_Pen = 1,
  CanvasObject_Stroke_FieldNumber_PathArray = 2,
};

@interface CanvasObject_Stroke : GPBMessage

@property(nonatomic, readwrite) BOOL hasPen;
@property(nonatomic, readwrite, strong, null_resettable) CanvasObject_Stroke_Pen *pen;

// |pathArray| contains |CanvasObject_Stroke_Path|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *pathArray;
@property(nonatomic, readonly) NSUInteger pathArray_Count;

@end

#pragma mark - CanvasObject_Stroke_Pen

typedef GPB_ENUM(CanvasObject_Stroke_Pen_FieldNumber) {
  CanvasObject_Stroke_Pen_FieldNumber_Mask = 1,
  CanvasObject_Stroke_Pen_FieldNumber_RgbColor = 2,
  CanvasObject_Stroke_Pen_FieldNumber_Thickness = 3,
};

@interface CanvasObject_Stroke_Pen : GPBMessage

@property(nonatomic, readwrite) CanvasObject_Stroke_Pen_Mask mask;

@property(nonatomic, readwrite) BOOL hasRgbColor;
@property(nonatomic, readwrite, strong, null_resettable) RGBColor *rgbColor;

@property(nonatomic, readwrite) float thickness;

@end

int32_t CanvasObject_Stroke_Pen_Mask_RawValue(CanvasObject_Stroke_Pen *message);
void SetCanvasObject_Stroke_Pen_Mask_RawValue(CanvasObject_Stroke_Pen *message, int32_t value);

#pragma mark - CanvasObject_Stroke_Path

typedef GPB_ENUM(CanvasObject_Stroke_Path_FieldNumber) {
  CanvasObject_Stroke_Path_FieldNumber_CurveType = 1,
  CanvasObject_Stroke_Path_FieldNumber_Point1 = 2,
  CanvasObject_Stroke_Path_FieldNumber_Point2 = 3,
  CanvasObject_Stroke_Path_FieldNumber_Point3 = 4,
};

@interface CanvasObject_Stroke_Path : GPBMessage

@property(nonatomic, readwrite) int32_t curveType;

@property(nonatomic, readwrite) BOOL hasPoint1;
@property(nonatomic, readwrite, strong, null_resettable) Point_Class *point1;

@property(nonatomic, readwrite) BOOL hasPoint2;
@property(nonatomic, readwrite, strong, null_resettable) Point_Class *point2;

@property(nonatomic, readwrite) BOOL hasPoint3;
@property(nonatomic, readwrite, strong, null_resettable) Point_Class *point3;

@end

#pragma mark - CanvasObject_Comment

typedef GPB_ENUM(CanvasObject_Comment_FieldNumber) {
  CanvasObject_Comment_FieldNumber_Comment = 1,
};

@interface CanvasObject_Comment : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *comment;

@end

#pragma mark - CanvasObject_Text

typedef GPB_ENUM(CanvasObject_Text_FieldNumber) {
  CanvasObject_Text_FieldNumber_Dimensions = 1,
  CanvasObject_Text_FieldNumber_FontSize = 2,
  CanvasObject_Text_FieldNumber_TextAlignment = 3,
  CanvasObject_Text_FieldNumber_TextColor = 4,
  CanvasObject_Text_FieldNumber_Text = 5,
};

@interface CanvasObject_Text : GPBMessage

@property(nonatomic, readwrite) BOOL hasDimensions;
@property(nonatomic, readwrite, strong, null_resettable) Dimensions *dimensions;

@property(nonatomic, readwrite) float fontSize;

@property(nonatomic, readwrite) CanvasObject_Text_TextAlignment textAlignment;

@property(nonatomic, readwrite) BOOL hasTextColor;
@property(nonatomic, readwrite, strong, null_resettable) RGBColor *textColor;

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@end

int32_t CanvasObject_Text_TextAlignment_RawValue(CanvasObject_Text *message);
void SetCanvasObject_Text_TextAlignment_RawValue(CanvasObject_Text *message, int32_t value);

#pragma mark - CanvasObject_VoiceNote

typedef GPB_ENUM(CanvasObject_VoiceNote_FieldNumber) {
  CanvasObject_VoiceNote_FieldNumber_AudioAttachmentId = 1,
};

@interface CanvasObject_VoiceNote : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *audioAttachmentId;

@end

#pragma mark - RGBColor

typedef GPB_ENUM(RGBColor_FieldNumber) {
  RGBColor_FieldNumber_Red = 1,
  RGBColor_FieldNumber_Green = 2,
  RGBColor_FieldNumber_Blue = 3,
};

@interface RGBColor : GPBMessage

@property(nonatomic, readwrite) int32_t red;

@property(nonatomic, readwrite) int32_t green;

@property(nonatomic, readwrite) int32_t blue;

@end

#pragma mark - Point_Class

typedef GPB_ENUM(Point_Class_FieldNumber) {
  Point_Class_FieldNumber_X = 1,
  Point_Class_FieldNumber_Y = 2,
};

@interface Point_Class : GPBMessage

@property(nonatomic, readwrite) float x;

@property(nonatomic, readwrite) float y;

@end

#pragma mark - Dimensions

typedef GPB_ENUM(Dimensions_FieldNumber) {
  Dimensions_FieldNumber_Width = 1,
  Dimensions_FieldNumber_Height = 2,
};

@interface Dimensions : GPBMessage

@property(nonatomic, readwrite) float width;

@property(nonatomic, readwrite) float height;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
