/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.RGBColor');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.RGBColor = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.RGBColor, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.RGBColor.displayName = 'proto.RGBColor';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.RGBColor.prototype.toObject = function(opt_includeInstance) {
  return proto.RGBColor.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.RGBColor} msg The msg instance to transform.
 * @return {!Object}
 */
proto.RGBColor.toObject = function(includeInstance, msg) {
  var f, obj = {
    red: msg.getRed(),
    green: msg.getGreen(),
    blue: msg.getBlue()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.RGBColor} The clone.
 */
proto.RGBColor.prototype.cloneMessage = function() {
  return /** @type {!proto.RGBColor} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 red = 1;
 * @return {number}
 */
proto.RGBColor.prototype.getRed = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.RGBColor.prototype.setRed = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 green = 2;
 * @return {number}
 */
proto.RGBColor.prototype.getGreen = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.RGBColor.prototype.setGreen = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 blue = 3;
 * @return {number}
 */
proto.RGBColor.prototype.getBlue = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.RGBColor.prototype.setBlue = function(value) {
  jspb.Message.setField(this, 3, value);
};


