/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Session');

goog.require('jspb.Message');
goog.require('proto.CanvasObject');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Session = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Session.repeatedFields_, null);
};
goog.inherits(proto.Session, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Session.displayName = 'proto.Session';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Session.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Session.prototype.toObject = function(opt_includeInstance) {
  return proto.Session.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Session} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Session.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: msg.getVersion(),
    clientid: msg.getClientid(),
    canvasobjectsList: jspb.Message.toObjectList(msg.getCanvasobjectsList(),
    proto.CanvasObject.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Session} The clone.
 */
proto.Session.prototype.cloneMessage = function() {
  return /** @type {!proto.Session} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 version = 1;
 * @return {number}
 */
proto.Session.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.Session.prototype.setVersion = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string clientId = 2;
 * @return {string}
 */
proto.Session.prototype.getClientid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.Session.prototype.setClientid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated CanvasObject canvasObjects = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.CanvasObject>}
 */
proto.Session.prototype.getCanvasobjectsList = function() {
  return /** @type{!Array.<!proto.CanvasObject>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.CanvasObject, 3));
};


/** @param {Array.<!proto.CanvasObject>|undefined} value  */
proto.Session.prototype.setCanvasobjectsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


proto.Session.prototype.clearCanvasobjectsList = function() {
  this.setCanvasobjectsList([]);
};


